/**
 * Write every named agent's A2A host into `wrangler.toml` as a Workers CUSTOM DOMAIN (spec 346 §5).
 *
 * WHY THIS EXISTS. `wrangler deploy` syncs a script's triggers to exactly what the config declares, so a
 * custom domain created out-of-band (dashboard or API) is DELETED by the next deploy of that Worker — with
 * its DNS record, taking every agent host offline. Learned the hard way on 2026-08-30: 36 hosts provisioned
 * by API vanished on the next deploy. Hosts therefore live HERE, in the config, and this script regenerates
 * the block from the estate's names.
 *
 * The alternative — one `*.<zone>/*` route — was tried the same day and reverted: on this account a
 * zone-level wildcard route OUTRANKED other scripts' custom domains, so demo-a2a answered for mcp / rpc /
 * discovery / edge / field (rpc returning 522 broke the Home). Do not re-add it without proving that
 * precedence has changed.
 *
 *   DISCOVERY_MCP=https://demo-discovery-mcp-faithnet.<acct>.workers.dev \
 *   ZONE=faithnet.io ENV=faithnet pnpm exec tsx scripts/sync-agent-hosts.ts [--write]
 *
 * Prints the block by default; `--write` splices it between the markers in wrangler.toml. Run it after a
 * new agent is named, then deploy.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { hostForName } from '../src/host-context';

const APP = join(import.meta.dirname ?? __dirname, '..');
const ENV = process.env.ENV ?? 'faithnet';
const ZONE = process.env.ZONE ?? 'faithnet.io';
const MCP = process.env.DISCOVERY_MCP ?? '';
const PARENTS = (process.env.AGENT_NAME_PARENTS ?? 'me,impact').split(',').map((p) => p.trim()).filter(Boolean);
const BEGIN = `# >>> agent hosts (${ENV}) — generated by scripts/sync-agent-hosts.ts; do not edit by hand`;
const END = `# <<< agent hosts (${ENV})`;

if (!MCP) throw new Error('DISCOVERY_MCP is required — the KB is where the named estate is enumerated');

const res = (await (await fetch(`${MCP}/search?q=&limit=500`)).json()) as { results?: Array<{ name?: string | null }> };
const names = [...new Set((res.results ?? []).map((r) => (r.name ?? '').trim().toLowerCase()).filter(Boolean))].sort();
const hosts = [...new Set(names.map((n) => hostForName(n, ZONE, PARENTS)).filter((h): h is string => !!h))].sort();

const block = [
  BEGIN,
  `# ${hosts.length} named agents in the ${ZONE} estate. A custom domain provisions its own DNS record and`,
  '# certificate; one label per host (spec 346 §5) keeps it inside the zone\'s existing wildcard certificate.',
  ...hosts.flatMap((h) => [`[[env.${ENV}.routes]]`, `pattern = "${h}"`, 'custom_domain = true', '']),
  END,
].join('\n');

const path = join(APP, 'wrangler.toml');
const toml = readFileSync(path, 'utf8');
if (!process.argv.includes('--write')) {
  console.log(block);
  console.error(`\n${hosts.length} hosts for ${names.length} names — re-run with --write to splice into wrangler.toml`);
} else {
  const i = toml.indexOf(BEGIN);
  const j = toml.indexOf(END);
  const next = i >= 0 && j > i ? toml.slice(0, i) + block + toml.slice(j + END.length) : `${toml.trimEnd()}\n\n${block}\n`;
  writeFileSync(path, next);
  console.error(`wrote ${hosts.length} agent hosts into wrangler.toml (env.${ENV}) — deploy to apply`);
}
